dataset:
  images_dir: "data/images"
  annotations_dir: "data/json"

  image_size:
    width: 1280
    height: 720

  normalize_boxes: true

  image_extensions:
    - ".jpg"
    - ".jpeg"
    - ".png"


video:
  videos_dir: "../bdd100k_downloads/VIDEOS_TEST/bdd100k/videos/100k/test"
  annotations_dir: "../out/labels3"

  # Опорным является последний кадр последовательности
  reference_frame: "last"

  # Сколько кадров взять ДО опорного
  frames_before: 4

  # Сколько кадров в секунду брать
  fps: 5


dataloader:
  batch_size: 4
  shuffle: true
  num_workers: 4

  pin_memory: true


classes:
  # Соответствие category из JSON -> числовой class_id

  'traffic light': 0
  'traffic sign': 1
  'car': 2
  'area/drivable': 3
  'lane/road curb': 4
  'person': 5
  'area/alternative': 6
  'lane/single white': 7
  'lane/double yellow': 8
  'bus': 9
  'truck': 10
  'lane/single yellow': 11
  'lane/crosswalk': 12
  'rider': 13
  'bike': 14
  'lane/double white': 15
  'motor': 16
  'train': 17
  'lane/single other': 18
  'lane/double other': 19
